version: '3.8'

services:
  # Databases
  codelabs_postgres_db: 
    image: docker.io/library/postgres:alpine3.18
    container_name: codelabs_postgres_db
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: codelabs
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
  
  codelabs_rabbitmq:
    image: docker.io/library/rabbitmq:3.12.11-management-alpine
    container_name: codelabs_rabbitmq
    restart: on-failure
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq
  
  # Microservices
  codelabs_static_files:
    image: ghcr.io/upb-code-labs/static-files-microservice:latest
    container_name: codelabs_static_files
    restart: on-failure
    ports:
      - "127.0.0.1:8081:8080"
    depends_on:
      - codelabs_postgres_db

  # Utils
  postgres_db_admin: 
    image: docker.io/dpage/pgadmin4:7.6
    container_name: postgres_db_admin
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - 5050:80