version: '3.8'

services:
  codelabs_postgres_db: 
    image: docker.io/library/postgres:alpine3.18
    container_name: codelabs_postgres_db
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: codelabs
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
  
  postgres_db_admin: 
    image: docker.io/dpage/pgadmin4:7.6
    container_name: postgres_db_admin
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - 5050:80