name: Coverage

on:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Setup Docker
        run: docker-compose up -d

      - name: Clean and coverage
        env: 
          EXEC_ENVIRONMENT: testing
        run: |
          export DB_MIGRATIONS_PATH=file://$(pwd)/sql/migrations
          go clean -cache
          go test -coverpkg ./... -coverprofile coverage.txt __tests__/integration/*.go

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          fail_ci_if_error: true
