name: Integration

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Clean and build
        run: |
          go clean -cache
          go build ./...

  lint:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Lint
        run: test -z $(gofmt -l src/**/*)

  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      # Todo: Add the docker-compose step when the file is ready

      - name: Test
        run: go test -p 1 -count 1 -v ./...
