name: Development Package

on:
  create: 
    tags:
      - "v*.*.*"

jobs:
  version:
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v3

      - name: Get latest version
        id: version
        run: |
          chmod u+x ./version.sh 
          ./version.sh >> $GITHUB_OUTPUT
  
  docker:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    needs:
      - version
    steps:
      - uses: actions/checkout@v3

      - name: Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:dev,ghcr.io/${{ github.repository }}:${{ needs.version.outputs.version }}