name: Tagging

on:
  push:
    branches:
      - dev

jobs:
  tag:
    permissions:
      contents: write

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: dev
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19.3.0
          cache: npm

      - name: Run standard version
        run: 'npx standard-version --message "[ci skip] chore(release): %s"'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
